# Generated by Django 3.2.3 on 2021-06-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price2',
            field=models.DecimalField(decimal_places=0, default=579, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price3',
            field=models.DecimalField(decimal_places=0, default=699, max_digits=4, null=True),
        ),
    ]
