# Generated by Django 3.1.7 on 2021-05-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('pizza', 'Пицца'), ('snacks', 'Закуски'), ('drink', 'Напитки')], max_length=50),
        ),
    ]
