# Generated by Django 3.2.3 on 2021-06-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_auto_20210605_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='size',
            field=models.CharField(default=0, max_length=32),
        ),
    ]
