# Generated by Django 3.1.7 on 2021-05-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_auto_20210508_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Пицца', 'Пицца'), ('Закуски', 'Закуски'), ('Напитки', 'Напитки')], max_length=50),
        ),
    ]
