# Generated by Django 3.2.3 on 2021-06-07 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'verbose_name': 'Промежуточная(Продукут - Корзина)', 'verbose_name_plural': 'Промежуточные(Продукут - Корзина)'},
        ),
    ]
