# Generated by Django 3.2.3 on 2021-06-01 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0006_alter_promotions_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotions',
            options={'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
    ]
