# Generated by Django 3.2.3 on 2021-06-01 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0007_alter_promotions_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza.coupon'),
        ),
    ]
