# Generated by Django 3.2.3 on 2021-05-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0007_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='sale',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=15, null=True, verbose_name='Купон'),
        ),
    ]
