# Generated by Django 3.2.3 on 2021-05-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0008_auto_20210515_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=15, verbose_name='Купон'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='sale',
            field=models.IntegerField(verbose_name='Скидка'),
        ),
    ]
