# Generated by Django 3.2.3 on 2021-06-01 16:34

import django.core.validators
from django.db import migrations, models
import pizza.models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0008_promotions_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='img',
            field=models.ImageField(null=True, upload_to='promotions/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='product/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png']), pizza.models.validate_image]),
        ),
    ]
