# Generated by Django 3.2.3 on 2021-06-01 16:37

import django.core.validators
from django.db import migrations, models
import pizza.models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0009_auto_20210601_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='img',
            field=models.ImageField(null=True, upload_to='promotions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg']), pizza.models.validate_image]),
        ),
    ]
