# Generated by Django 3.2.3 on 2021-05-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0010_alter_coupon_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='sale',
            field=models.IntegerField(verbose_name='Скидка'),
        ),
    ]
