# Generated by Django 3.2.3 on 2021-05-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0011_alter_coupon_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to='pizza.UserData'),
        ),
    ]
