# Generated by Django 3.2.3 on 2021-05-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0013_alter_coupon_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='users',
        ),
        migrations.AddField(
            model_name='userdata',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_coupon', to='pizza.Coupon'),
        ),
    ]
