# Generated by Django 3.2.3 on 2021-05-15 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0014_auto_20210515_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='users',
            new_name='coupon',
        ),
    ]
