# Generated by Django 3.2.3 on 2021-05-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0015_rename_users_userdata_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_order', to='pizza.Order', verbose_name='Заказы покупателя'),
        ),
    ]
