# Generated by Django 3.2.3 on 2021-05-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0016_alter_userdata_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='coupon',
        ),
        migrations.AddField(
            model_name='coupon',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_coupon', to='pizza.UserData'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='orders',
            field=models.ManyToManyField(related_name='related_order', to='pizza.Order', verbose_name='Заказы покупателя'),
        ),
    ]
