# Generated by Django 3.2.2 on 2021-05-16 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0017_auto_20210515_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='sale',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка'),
        ),
    ]
