# Generated by Django 3.2.2 on 2021-05-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0018_alter_coupon_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=15, unique=True, verbose_name='Купон'),
        ),
    ]
