# Generated by Django 3.2.2 on 2021-05-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0019_alter_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_coupon_activate',
            field=models.BooleanField(default=False),
        ),
    ]
