# Generated by Django 3.2.2 on 2021-05-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0021_cart_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='users',
        ),
    ]
