# Generated by Django 3.2.1 on 2021-05-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0024_auto_20210524_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='anonymous',
        ),
        migrations.AddField(
            model_name='userdata',
            name='session',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
